config/routes.rb
Rails.application.routes.draw do
  resources :groups

  root "welcome#home"
  get 'welcome/home'

  get 'welcome/ajax'
  get 'welcome/ajax2'
  get 'welcome/about'
  get 'welcome/samplejson'

  devise_for :users
  
  resources :blog_comments

  resources :blog_posts

  resources :blogs

end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base

	belongs_to :blog

	has_many :blog_comments
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :set_blog_post, only: [:show, :edit, :update, :destroy]

  # GET /blog_posts
  # GET /blog_posts.json
  def index
    @blog_posts = BlogPost.all
  end

  # GET /blog_posts/1
  # GET /blog_posts/1.json
  def show

    @blog_comment = BlogComment.new
  end

  # GET /blog_posts/new
  def new
    @blog_post = BlogPost.new
  end

  # GET /blog_posts/1/edit
  def edit
  end

  # POST /blog_posts
  # POST /blog_posts.json
  def create
    @blog_post = BlogPost.new(blog_post_params)

    respond_to do |format|
      if @blog_post.save
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully created.' }
        format.json { render :show, status: :created, location: @blog_post }
      else
        format.html { render :new }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog_posts/1
  # PATCH/PUT /blog_posts/1.json
  def update
    respond_to do |format|
      if @blog_post.update(blog_post_params)
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog_post }
      else
        format.html { render :edit }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_posts/1
  # DELETE /blog_posts/1.json
  def destroy
    @blog_post.destroy
    respond_to do |format|
      format.html { redirect_to blog_posts_url, notice: 'Blog post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_post
      @blog_post = BlogPost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_post_params
      params.require(:blog_post).permit(:blog_id, :title, :body)
    end
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper

	def update_num_comments(blogpost_id)

		blog_post = BlogPost.find(blogpost_id)

		num_comments = blog_post.comments.count

		blog_post.num_comments = num_comments
		blog_post.save

	end
end

app/views/blog_posts/_form.html.erb
<%= form_for(@blog_post) do |f| %>
  <% if @blog_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog_post.errors.count, "error") %> prohibited this blog_post from being saved:</h2>

      <ul>
      <% @blog_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :blog_id %><br>
    <%= f.number_field :blog_id %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blog_posts/edit.html.erb
<h1>Editing blog_post</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog_post %> |
<%= link_to 'Back', blog_posts_path %>

app/views/blog_posts/index.html.erb
<h1>Listing blog_posts</h1>

<table>
  <thead>
    <tr>
      <th>Blog</th>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blog_posts.each do |blog_post| %>
      <tr>
        <td><%= blog_post.blog_id %></td>
        <td><%= blog_post.title %></td>
        <td><%= blog_post.body %></td>
        <td><%= link_to 'Show', blog_post %></td>
        <td><%= link_to 'Edit', edit_blog_post_path(blog_post) %></td>
        <td><%= link_to 'Destroy', blog_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog post', new_blog_post_path %>

app/views/blog_posts/new.html.erb
<h1>New blog_post</h1>

<%= render 'form' %>

<%= link_to 'Back', blog_posts_path %>

app/views/blog_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Blog:</strong>
  <%= @blog_post.blog_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @blog_post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog_post.body %>
</p>

<%if @blog_post.num_comments == 0 || @blog_post.num_comments == nil%>
	Sorry, no comments you guys
	<Br><br>
<%else%>

	<table>
	  <thead>
	    <tr>
	      <th>Blogpost</th>
	      <th>Comment</th>
	      <th colspan="3"></th>
	    </tr>
	  </thead>

	  <tbody>
	    <%@blog_post.blog_comments.each do |blog_comment|%>
	      <tr>
	        <td><%= blog_comment.blog_post_id %></td>
	        <td><%= blog_comment.comment %></td>
	        <td><%= link_to 'Show', blog_comment %></td>
	        <td><%= link_to 'Edit', edit_blog_comment_path(blog_comment) %></td>
	        <td><%= link_to 'Destroy', blog_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	      </tr>
	    <% end %>
	  </tbody>
	</table>
<%end%>

This is the form?

<%= render 'blog_comments/form' %>


<%= link_to 'Edit', edit_blog_post_path(@blog_post) %> |
<%= link_to 'Back', blog_posts_path %>