config/routes.rb
Rails.application.routes.draw do
  resources :groups

  root "welcome#home"
  get 'welcome/home'

  get 'welcome/ajax'
  get 'welcome/ajax2'
  get 'welcome/about'
  get 'welcome/samplejson'

  devise_for :users
  
  resources :blog_comments

  resources :blog_posts

  resources :blogs

end

app/models/blog_comment.rb
class BlogComment < ActiveRecord::Base

	belongs_to :blog_post
end

app/controllers/blog_comments_controller.rb
class BlogCommentsController < ApplicationController
  before_action :set_blog_comment, only: [:show, :edit, :update, :destroy]

  include BlogPostsHelper

  # GET /blog_comments
  # GET /blog_comments.json
  def index
    @blog_comments = BlogComment.all
  end

  # GET /blog_comments/1
  # GET /blog_comments/1.json
  def show
  end

  # GET /blog_comments/new
  def new
    @blog_comment = BlogComment.new
    @blog_post = params[:blog_post_id]
  end

  # GET /blog_comments/1/edit
  def edit
  end

  # POST /blog_comments
  # POST /blog_comments.json
  def create
    @blog_comment = BlogComment.new(blog_comment_params)

    respond_to do |format|
      if @blog_comment.save

        #update number of comments
        update_num_comments @blog_comment.blogpost_id

        format.html { redirect_to @blog_comment.blog_post, notice: 'Blog comment was successfully created.' }
        format.json { render :show, status: :created, location: @blog_comment }
      else
        format.html { render :new }
        format.json { render json: @blog_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog_comments/1
  # PATCH/PUT /blog_comments/1.json
  def update
    respond_to do |format|

      old_blog_post_id = @blog_comment.blogpost_id

      if @blog_comment.update(blog_comment_params)

        # remove from old
        update_num_comments old_blog_post_id

        # add to new
        update_num_comments @blog_comment.blogpost_id


        format.html { redirect_to @blog_comment, notice: 'Blog comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog_comment }
      else
        format.html { render :edit }
        format.json { render json: @blog_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_comments/1
  # DELETE /blog_comments/1.json
  def destroy

    blogpost_id = @blog_comment.blogpost_id

    @blog_comment.destroy

    update_num_comments blogpost_id

    respond_to do |format|
      format.html { redirect_to blog_comments_url, notice: 'Blog comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_comment
      @blog_comment = BlogComment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_comment_params
      params.require(:blog_comment).permit(:blog_post_id, :comment)
    end
end

app/helpers/blog_comments_helper.rb
module BlogCommentsHelper
end

app/views/blog_comments/_form.html.erb
<%= form_for(@blog_comment) do |f| %>
  <% if @blog_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog_comment.errors.count, "error") %> prohibited this blog_comment from being saved:</h2>

      <ul>
      <% @blog_comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :blog_post_id %><br>
    <%= f.number_field :blog_post_id %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blog_comments/edit.html.erb
<h1>Editing blog_comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog_comment %> |
<%= link_to 'Back', blog_comments_path %>

app/views/blog_comments/index.html.erb
<h1>Listing blog_comments</h1>

<table>
  <thead>
    <tr>
      <th>Blogpost</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blog_comments.each do |blog_comment| %>
      <tr>
        <td><%= blog_comment.blogpost_id %></td>
        <td><%= blog_comment.comment %></td>
        <td><%= link_to 'Show', blog_comment %></td>
        <td><%= link_to 'Edit', edit_blog_comment_path(blog_comment) %></td>
        <td><%= link_to 'Destroy', blog_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog comment', new_blog_comment_path %>

app/views/blog_comments/new.html.erb
<h1>New blog_comment</h1>

<%= render 'form' %>

<%= link_to 'Back', blog_comments_path %>

app/views/blog_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Blogpost:</strong>
  <%= @blog_comment.blogpost_id %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @blog_comment.comment %>
</p>

<%= link_to 'Edit', edit_blog_comment_path(@blog_comment) %> |
<%= link_to 'Done', @blog_comment.blog_post %>